### ISSUE TITLE
Unable to save s-matrix to MAT file from Simphony in Klayout

### ISSUE THREAD

**Issue by rumbonium** [BYUCamachoLab/simphony#12]
Any attempt to 'Export s-matrix' throws the following error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/hygunth/.klayout/python/SiEPIC_Simphony/single_port_simulation.py", line 171, in export_s_matrix
    s_mat, freq = self.simulation.exportSMatrix()
AttributeError: 'Simulation' object has no attribute 'exportSMatrix'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/hygunth/.klayout/python/SiEPIC_Simphony/single_port_simulation.py", line 171, in export_s_matrix
    s_mat, freq = self.simulation.exportSMatrix()
AttributeError: 'Simulation' object has no attribute 'exportSMatrix'
```

Steps to reproduce:
1. Open or create a layout that Simphony can simulate
2. Click 'Simphony Simulation'
3. Once the simulation has run and the tk window pops up, click 'Export s-matrix' under the 'File' menu.

**Comment by sequoiap** [comment]
With the rewritten simphony release coming soon (v0.3.0), this issue becomes obsolete.
