### ISSUE TITLE
Cannot run the Layout-Aware example

### ISSUE THREAD

**Issue by vmetodiev** [BYUCamachoLab/simphony#87]
On the latest master branch commit, even if gdsfactory is installed, upon trying to run the "Layout-Aware Monte Carlo Simulations for Yield Estimation" [example](https://simphonyphotonics.readthedocs.io/en/latest/tutorials/layout_aware.html) from the official documentation page, I get:

2023-07-08 18:51:59.778 | INFO     | gdsfactory.config:__init__:205 - LogLevel: INFO
2023-07-08 18:52:01.503 | WARNING  | gdsfactory.types:<module>:47 - gdsfactory.types has been renamed to gdsfactory.typings. types will be removed in the near future.
2023-07-08 18:52:01.749 | WARNING  | gdsfactory.pdk:get_active_pdk:621 - No active PDK. Activating generic PDK.

2023-07-08 18:52:01.934 | INFO     | gdsfactory.technology.layer_views:__init__:785 - Importing LayerViews from YAML file: '/usr/local/lib/python3.8/dist-packages/gdsfactory/generic_tech/layer_views.yaml'.
2023-07-08 18:52:01.945 | INFO     | gdsfactory.pdk:activate:266 - 'generic' PDK is now active
Traceback (most recent call last):
  File "sim.py", line 62, in <module>
    c = mzi()
  File "/usr/local/lib/python3.8/dist-packages/gdsfactory/cell.py", line 186, in _cell
    component = func(*args, **kwargs)
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "sim.py", line 33, in mzi
    gc_input["pin1"].connect(y_splitter, gcin, ysplit)
  File "/home/ubuntu/Work/Photonics/simphony/simphony/pins.py", line 104, in connect
    raise ImportError("gdsfactory is not installed. Try `pip install gdsfactory`.")
ImportError: gdsfactory is not installed. Try `pip install gdsfactory`.

_Note: I have created the sim.py file that contains the copy-pasted snippets from the tutorial and is located inside the repo  root directory. _

**Comment by sequoiap** [comment]
@cjcarver @SkandanC

**Comment by sequoiap** [comment]
gdsfactory's API changes frequently, so it's possible that the latest versions of gdsfactory don't work with this example anymore. @SkandanC, any ideas on how far back of a reversion might be required?

I'll also mention that simphony is presently undergoing a pretty major refactoring to be released as v0.7.0 (and it will be incompatible with previous versions). The new API will be much prettier, in my opinion as the developer, so we probably won't be trying very hard to get the old versions of simphony to work with gdsfactory again but focus our efforts on the new one.
